name: CI

on:
  - push

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          npm i

      - name: build
        run: |
          npm run build

      - name: lint
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          npm run lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run test-coverage
          debug: true
